### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by tarcieri** [fizyk20/generic-array#101]
This crate has become a pretty foundational part of a few Rust ecosystems:

- Embedded (via `heapless` and other fixed-sized containers)
- RustCrypto (where we just completed a `generic-array` v0.14 upgrade)

Unfortunately, if you now use both `heapless` and RustCrypto in conjunction (via RustCrypto's `aead::heapless` for example) it pulls in `generic-array` v0.12, v0.13, and v0.14! (this is due to the [`as-slice`](https://github.com/japaric/as-slice/blob/master/Cargo.toml#L13-L14) crate, which pulls in both v0.12 and v0.13 for whatever reason)

In addition to eliminating confusion around coordinating `generic-array` upgrades, a 1.0 release of `generic-array` is one of the main blockers for a 1.0 release of many of the RustCrypto crates, so it'd be fantastic if that were to happen.

Any thoughts on a 1.0 release?

**Comment by burdges** [comment]
https://github.com/fizyk20/generic-array/issues/56

**Comment by novacrazy** [comment]
I'm looking to merge #104 soon. Are there any additions or breaking changes that come to mind for a 1.0 release?

**Comment by Robbepop** [comment]
> I'm looking to merge #104 soon. Are there any additions or breaking changes that come to mind for a 1.0 release?

Not sure if these would be breaking changes but we could improve support for `&GenericArray<T, N>` and `&mut GenericArray<T, N>`. I pushed into this direction with my current and former PRs but there is more we could do.

We already established that `GenericArray<T, N>` is similar to `[T; N]` and `&GenericArray<T, N>` as well as `&mut GenericArray<T, N>` are similar to `&[T, N]` and `&mut [T, N]` respectively. They should be able to be used interchangeably with minimal effort and at best as drop in replacement for when you need more control over the `N`.

In this regard I see potential in implementing `Shorten` (and maybe also `Lengthen`) for those reference types and not just for the value part:
![2020-06-16-224229_1570x373_scrot](https://user-images.githubusercontent.com/8193155/84826103-bf1dcf80-b022-11ea-80d8-96bd4cc26d65.png)
![2020-06-16-224527_1578x589_scrot](https://user-images.githubusercontent.com/8193155/84826356-20de3980-b023-11ea-8826-08b885b3770c.png)

Same for `Send` and `Sync` if `&[T; N]` or `&mut [T; N]` is `Send` or `Sync` respectively.
Also an `IntoIterator` for the reference types yielding `&T` and `&mut T` respectively could be useful as with:
![2020-06-16-224722_1811x660_scrot](https://user-images.githubusercontent.com/8193155/84826531-5d119a00-b023-11ea-955f-9165a0bd80a5.png)
Especially since we can even provide an `ExactSizeIterator` in both cases.

But all in all none of these are to my opinion breaking changes so we could probably introduce them post 1.0.

**Comment by novacrazy** [comment]
See #138 for the current status of this. Looking for feedback and ideas.

**Comment by novacrazy** [comment]
[`generic-array` 1.0.0 has been published!](https://crates.io/crates/generic-array/1.0.0)
