### ISSUE TITLE
Why does ArrayLength need to be generic over the array type

### ISSUE THREAD

**Issue by neon64** [fizyk20/generic-array#14]
I have several methods like this that take two type parameters because I'm using two different GenericArrays. The array lengths themselves should be always equal to each other.

    pub fn do_something<N: ArrayLength<StructA>, P: ArrayLength<StructB>>(...) {}

Is there a reason why it is `ArrayLength<T>` instead of just `ArrayLength`, or is there some way this function can be generic over just one `ArrayLength` type and the other one is created from the first?

**Comment by fizyk20** [comment]
It is basically due to the fact that I haven't been able to come up with a better design.

The `ArrayLength<T>` trait has an associated type which is used in the `GenericArray` struct as a placeholder for the data. This associated type is what does all the magic in allocating exactly as much memory as is needed. The problem is, this amount of memory depends on both the number represented by the type implementing `ArrayLength` and the type of data to be stored in the array. So, this associated type has to know both of the array length (which is the type implementing the trait) and of the data type (which is passed as a generic parameter). Hence `ArrayLength<T>`.

**Comment by neon64** [comment]
Ok thanks for the helpful explanation. I suppose this crate could benefit from const mem::size_of() and/or const functions in traits, because then you could write something like

```rust
trait ArrayLength {
    const fn size() -> usize;
}

let array = [0; U2::size()];
```

Also one more question, is it possible to implement the `Serialize` and `Deserialize` from Serde in this library. I tried to do it my own crate but I got stuck fighting the orphaning rules. If it is something you desire, I could implement it and open a PR. I think all that is needed is

```rust
impl<T, N: ArrayLength<T>> Serialize for GenericArray<T, N>
    where T: Serialize {
    #[inline]
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer,
    {
        serializer.serialize_seq(SeqIteratorVisitor::new(self.iter(), Some(self.len())))
    }
}
```

and something similar for deserialization

**Comment by fizyk20** [comment]
Yeah, should be possible, although I would probably have to look into the possibilities for defining optional dependencies - I don't want users of this crate to have to download lots of dependencies they don't need ;)

**Comment by neon64** [comment]
Good point. A week ago I was 90% there implementing that feature using cargo features and conditional compilation. I think I just need to write some tests for it an then I'll open a pr.

**Comment by gnzlbg** [comment]
@fizyk20 

> It is basically due to the fact that I haven't been able to come up with a better design.

I've fixed this in my local copy of `GenericArray` using specialization because having to write the `where: U: ArrayLength<T>` in every struct/impl/fn that uses `GenericArray` was giving me OCD. 

While I think it would significantly improve the ergonomics of `GenericArray`, I don't know whether you would be ok to making the crate require unstable. 

Also, if one decides to require unstable Rust, it is possible that other features like associated consts might further improve the ergonomics as well (although I think associated consts are currently highly limited).
