### ISSUE TITLE
Support from/into array up to 64

### ISSUE THREAD

**Issue by singpolyma-shopify** [fizyk20/generic-array#79]
Currently only support up to 32

**Comment by novacrazy** [comment]
The standard library currently only supports most traits on arrays up to length 32, so having `From`/`Into` implementations beyond that feels odd.

@fizyk20 Do you have an opinions on this? It would be super easy to do. 

Maybe also implement it for powers of 2 and 10.

**Comment by fizyk20** [comment]
We can't implement it for every number, so we have to stop somewhere, and the sizes supported by `std` seem to be a natural point.

But of course nothing stands in the way of being a bit better than `std` ;) I don't have an opinion here, really - slightly leaning towards doing it, though, since it's obviously useful to someone.

**Comment by novacrazy** [comment]
I find it kind of funny that `std` *just* re-implemented a lot of array things using `const` generics. In fact, they had to artificially restrict it to 32 for temporary compatibility. We're being phased out by the day... 😄 

Anyway, simple transmutes are so small that adding more it probably won't bloat up compile times much. Might as well.

**Comment by novacrazy** [comment]
Added in `0.13.2`
