### ISSUE TITLE
`arr!` unsoundness

### ISSUE THREAD

**Issue by jswrenn** [fizyk20/generic-array#98]
The `arr!` macro silently and unsoundly extends arbitrary lifetimes to `'static` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2160bea8c1d3b5abf517518afa94024b)):
```rust
fn unsound_lifetime_extension<'a, A>(a: &'a A) -> &'static A {
  arr![&A; a][0]
}
```

**Comment by novacrazy** [comment]
Hmm. This is more problematic than I expected.

What's happening is that `&A` being sent into a macro is not turned into a concrete type until the macro has generated the code. For the above, it generates this code:
```rust
unsafe { transmute::<[&A; 1], GenericArray<&A, 1>>([a]) }
```
and then the lifetimes are filled in on either side of the transmute using `'a` and `'static` via lifetime elusion, but transmuting does allow it to be changed incorrectly.

What I need to figure out is how to ensure `&'_ A == &'_ A` without disrupting lifetime elusion entirely.

For example,
```rust
type T = $T;
unsafe { transmute::<[T; 1], GenericArray<T, 1>>([a]) }
```
ensures that the input and output element types are the exact same, including lifetimes. However, it disables lifetime elusion entirely, so no structs with lifetimes can be passed unless the type includes the (often anonymous) lifetime. So that's a no-go.

Furthermore, because const-generics aren't a thing yet, or else this library wouldn't still be used,  I cannot perform the transmute within a closed-form function that would otherwise ensure the input and output element types are the same.

**Comment by Shnatsel** [comment]
Heads up: this issue [has been included](https://github.com/RustSec/advisory-db/pull/780) in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on for affected versions of this crate.

**Comment by greyblake** [comment]
@Shnatsel 
FYI, @fizyk20 just released patched old versions:
* 0.12.4
* 0.13.3
* 0.11.2
* 0.10.1
* 0.9.1

See:
* https://crates.io/crates/generic-array/versions
* https://github.com/fizyk20/generic-array/pull/99#issuecomment-788866544

**Comment by fizyk20** [comment]
Still working on 0.8.4 (0.8.3 is also vulnerable), but it looks like crates.io is having some DNS issues (can't resolve static.crates.io... or is it just me?).

**Comment by greyblake** [comment]
@fizyk20 Looks good to me!
![image](https://user-images.githubusercontent.com/113512/109654125-1a1c3600-7b62-11eb-83ea-6b5817835385.png)

Thank you!
I opened PR to RustSec: https://github.com/RustSec/advisory-db/pull/789

**Comment by mbrubeck** [comment]
PSA: Now that the fix has been backported to all affected release branches, anyone affected by this can now fix it by running:

```
cargo update -p generic-array
```

This may return an error if your dependencies use multiple versions of `generic-array`.  You can fix this error by specifying the exact version that you want to upgrade from.  For example:

```
cargo update -p generic-array:0.12.3
```
